steps:
  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      [
        "run",
        "deploy",
        "backend-dex-api-prod",
        "--image",
        "us-central1-docker.pkg.dev/upshot-423406/docker/backend:dex-$TAG_NAME",
        "--region",
        "us-central1",
      ]
options:
  logging: CLOUD_LOGGING_ONLY
