packages:
  - apps/*
  - packages/*
  - server/*

catalog:
  '@tanstack/react-query': ^5.62.7
  '@ts-rest/core': ^3.51.0
  '@types/eslint': ^9.6.1
  '@types/react': ^19.0.7
  axios: ^1.10.0
  eslint: ^9.23.0
  prettier: ^3.5.3
  react: ^19.0.0
  typescript: 5.8.3
  typescript-eslint: ^8.32.0
  zod: 3.25.76
