packages:
  - apps/*
  - '!apps/prod-ref-web'
  - packages/*
  - server/*

catalog:
  '@tanstack/react-query': 5.90.5
  '@ts-rest/core': ^3.51.0
  '@ts-rest/express': ^3.51.0
  '@types/eslint': ^9.6.1
  '@types/react': ^19.0.7
  axios: 1.13.1
  dayjs: ^1.11.19
  eslint: ^9.23.0
  postgres: ^3.4.7
  prettier: ^3.5.3
  react: ^19.0.0
  tsx: ^4.19.2
  typescript: 5.8.3
  typescript-eslint: ^8.32.0
  zod: 3.25.76
