/**
 * B2B Client DTO - Request/Response Types
 * Used for API ↔ UseCase communication
 */

export interface ClientBankAccountDTO {
  currency: string;
  bank_name: string;
  account_number: string;
  account_name: string;
  bank_details?: Record<string, any>;
}

export interface CreateClientRequest {
  // Privy account info (stored in privy_accounts table)
  privyOrganizationId: string;
  privyWalletAddress: string;
  privyEmail?: string;
  walletType: 'custodial' | 'non-custodial';

  // Vault creation options (token-centric: each token supports ALL 5 chains)
  vaultsToCreate?: 'usdc' | 'usdt' | 'both'; // Which token vaults to create, defaults to "both" (creates 10 vaults: 5 chains × 2 tokens)

  // Organization info (stored in client_organizations table)
  productId: string;
  companyName: string;
  businessType: string;
  description?: string;
  websiteUrl?: string;
  customerTier?: string; // AUM tier: 0-1K | 1K-10K | 10K-100K | 100K-1M | 1M+
  strategyRanking?: string[]; // Array of strategy IDs in order of preference

  // API credentials (auto-generated, not provided in request)
  // apiKeyHash and apiKeyPrefix are generated by the system
  webhookUrls?: string[];
  webhookSecret?: string;

  // Strategy & fees
  customStrategy?: any;

  // Fee Configuration (3-way revenue split: Platform + Client + End-User = 100%)
  clientRevenueSharePercent?: string; // 10-20%, defaults to 15.00
  platformFeePercent?: string; // 5-10%, defaults to 7.50
  performanceFee?: string;

  // Multi-currency support (for off-ramp withdrawals)
  supportedCurrencies?: string[];
  bankAccounts?: ClientBankAccountDTO[];

  // Status
  isActive?: boolean;
  isSandbox?: boolean;
}

export interface AddFundsRequest {
  clientId: string;
  amount: string;
  source: string;
  reference?: string;
}

export interface ReserveFundsRequest {
  clientId: string;
  amount: string;
  purpose: string;
  reference?: string;
}

export interface ReleaseFundsRequest {
  clientId: string;
  amount: string;
  purpose: string;
  reference?: string;
}

export interface DeductReservedRequest {
  clientId: string;
  amount: string;
  purpose: string;
  reference?: string;
}
