/**
 * B2B Client DTO - Request/Response Types
 * Used for API ↔ UseCase communication
 */

export interface CreateClientRequest {
  // Privy account info (stored in privy_accounts table)
  privyOrganizationId: string;
  privyWalletAddress: string;
  privyEmail?: string;
  walletType: 'custodial' | 'non-custodial';

  // Vault creation options (token-centric: each token supports ALL 5 chains)
  vaultsToCreate?: 'usdc' | 'usdt' | 'both'; // Which token vaults to create, defaults to "both" (creates 10 vaults: 5 chains × 2 tokens)

  // Organization info (stored in client_organizations table)
  productId: string;
  companyName: string;
  businessType: string;
  description?: string;
  websiteUrl?: string;

  // API credentials (auto-generated, not provided in request)
  // apiKeyHash and apiKeyPrefix are generated by the system
  webhookUrls?: string[];
  webhookSecret?: string;

  // Strategy & fees
  customStrategy?: any;
  endUserYieldPortion?: string;
  platformFee?: string;
  performanceFee?: string;

  // Status
  isActive?: boolean;
  isSandbox?: boolean;
}

export interface AddFundsRequest {
  clientId: string;
  amount: string;
  source: string;
  reference?: string;
}

export interface ReserveFundsRequest {
  clientId: string;
  amount: string;
  purpose: string;
  reference?: string;
}

export interface ReleaseFundsRequest {
  clientId: string;
  amount: string;
  purpose: string;
  reference?: string;
}

export interface DeductReservedRequest {
  clientId: string;
  amount: string;
  purpose: string;
  reference?: string;
}
