/**
 * API Key Utilities
 * Following Stripe's pattern for production-grade API keys
 */

import { randomBytes } from "crypto"

import bcrypt from "bcrypt"

const SALT_ROUNDS = 10

/**
 * Generate a new API key
 * Format: pk_{environment}_{random32chars} (Stripe-style)
 *
 * Examples:
 *   pk_live_7a9f3e2b1c4d8f6e5a0b9c8d7e6f5a4b  (Production)
 *   pk_test_1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f  (Sandbox)
 *
 * @param isSandbox - Whether this is a sandbox/test key
 * @returns Secure API key (shown only once!)
 */
export function generateApiKey(isSandbox = false): string {
	const env = isSandbox ? "test" : "live"
	const random = randomBytes(16).toString("hex") // 32 hex chars
	return `pk_${env}_${random}`
}

/**
 * Hash API key for secure storage
 * Uses bcrypt with configurable salt rounds (default: 10)
 *
 * @param apiKey - Plain text API key
 * @returns Bcrypt hash (safe to store in database)
 */
export async function hashApiKey(apiKey: string): Promise<string> {
	return await bcrypt.hash(apiKey, SALT_ROUNDS)
}

/**
 * Verify API key against stored hash
 * Constant-time comparison via bcrypt
 *
 * @param apiKey - Plain text API key from request
 * @param hash - Stored bcrypt hash
 * @returns True if key matches hash
 */
export async function verifyApiKey(apiKey: string, hash: string): Promise<boolean> {
	return await bcrypt.compare(apiKey, hash)
}

/**
 * Extract API key prefix for fast database lookup
 * Prefix is first 16 characters (pk + environment + first 8 hex chars)
 * This ensures uniqueness per product (~4 billion combinations)
 *
 * Examples:
 *   pk_live_7a9f3e2b (Production)
 *   pk_test_1c2d3e4f (Sandbox)
 *
 * @param apiKey - Full API key
 * @returns First 16 characters (e.g., "pk_live_8ad2f1c3")
 */
export function extractPrefix(apiKey: string): string {
	return apiKey.substring(0, 16)
}

/**
 * Validate API key format
 * Must match: pk_{live|test}_{32 hex chars}
 *
 * @param apiKey - API key to validate
 * @returns True if format is valid
 */
export function isValidApiKeyFormat(apiKey: string): boolean {
	const pattern = /^pk_(live|test)_[a-f0-9]{32}$/
	return pattern.test(apiKey)
}

/**
 * Check if an API key is a demo key (client-side generated from prefix)
 * Demo keys are generated by repeating the 8-char prefix 3 times
 *
 * Format:
 *   Prefix: pk_test_3084db68 (16 chars)
 *   Demo key: pk_test_3084db683084db683084db68 (40 chars - prefix repeated 3x)
 *   Real key: pk_test_7a9f3e2b1c4d8f6e5a0b9c8d7e6f5a4b (40 chars - random)
 *
 * @param apiKey - Full API key to check
 * @returns True if this is a demo key (repeated pattern)
 */
export function isDemoApiKey(apiKey: string): boolean {
	// Demo keys are 40 chars: pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
	if (!apiKey.match(/^pk_(test|live)_[a-f0-9]{32}$/)) {
		return false
	}

	// Extract the hex part (32 chars after "pk_test_" or "pk_live_")
	const hexPart = apiKey.substring(8)

	// Check if last 24 chars are repeated pattern of first 8 chars
	const firstSegment = hexPart.substring(0, 8)
	const extension = (firstSegment + firstSegment + firstSegment).substring(0, 24)

	return hexPart.substring(8) === extension
}
