/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PaymentSessionOrderIdRouteImport } from './routes/payment-session.$orderId'
import { Route as DashboardProductConfigRouteImport } from './routes/dashboard/product-config'
import { Route as DashboardOperationsRouteImport } from './routes/dashboard.operations'
import { Route as DashboardMarketRouteImport } from './routes/dashboard/market'
import { Route as DashboardIntegrationRouteImport } from './routes/dashboard/integration'
import { Route as DashboardExploreRouteImport } from './routes/dashboard/explore'
import { Route as DashboardDocsRouteImport } from './routes/dashboard/docs'
import { Route as DashboardApiTestingRouteImport } from './routes/dashboard/api-testing'
import { Route as DashboardAnalyticsRouteImport } from './routes/dashboard/analytics'
import { Route as DashboardProductsIndexRouteImport } from './routes/dashboard/products/index'
import { Route as DashboardPortfoliosIndexRouteImport } from './routes/dashboard/portfolios/index'
import { Route as DashboardProductsProductIdRouteImport } from './routes/dashboard/products/$productId'
import { Route as DashboardPortfoliosIdRouteImport } from './routes/dashboard/portfolios/$id'
import { Route as AuthenticatedOnboardingCreateProductRouteImport } from './routes/_authenticated/onboarding/create-product'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PaymentSessionOrderIdRoute = PaymentSessionOrderIdRouteImport.update({
  id: '/payment-session/$orderId',
  path: '/payment-session/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProductConfigRoute = DashboardProductConfigRouteImport.update({
  id: '/product-config',
  path: '/product-config',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOperationsRoute = DashboardOperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMarketRoute = DashboardMarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardIntegrationRoute = DashboardIntegrationRouteImport.update({
  id: '/integration',
  path: '/integration',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardExploreRoute = DashboardExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocsRoute = DashboardDocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardApiTestingRoute = DashboardApiTestingRouteImport.update({
  id: '/api-testing',
  path: '/api-testing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAnalyticsRoute = DashboardAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsIndexRoute = DashboardProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPortfoliosIndexRoute =
  DashboardPortfoliosIndexRouteImport.update({
    id: '/portfolios/',
    path: '/portfolios/',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardProductsProductIdRoute =
  DashboardProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => DashboardRoute,
  } as any)
const DashboardPortfoliosIdRoute = DashboardPortfoliosIdRouteImport.update({
  id: '/portfolios/$id',
  path: '/portfolios/$id',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthenticatedOnboardingCreateProductRoute =
  AuthenticatedOnboardingCreateProductRouteImport.update({
    id: '/onboarding/create-product',
    path: '/onboarding/create-product',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-testing': typeof DashboardApiTestingRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/integration': typeof DashboardIntegrationRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/product-config': typeof DashboardProductConfigRoute
  '/payment-session/$orderId': typeof PaymentSessionOrderIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/onboarding/create-product': typeof AuthenticatedOnboardingCreateProductRoute
  '/dashboard/portfolios/$id': typeof DashboardPortfoliosIdRoute
  '/dashboard/products/$productId': typeof DashboardProductsProductIdRoute
  '/dashboard/portfolios': typeof DashboardPortfoliosIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-testing': typeof DashboardApiTestingRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/integration': typeof DashboardIntegrationRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/product-config': typeof DashboardProductConfigRoute
  '/payment-session/$orderId': typeof PaymentSessionOrderIdRoute
  '/dashboard': typeof DashboardIndexRoute
  '/onboarding/create-product': typeof AuthenticatedOnboardingCreateProductRoute
  '/dashboard/portfolios/$id': typeof DashboardPortfoliosIdRoute
  '/dashboard/products/$productId': typeof DashboardProductsProductIdRoute
  '/dashboard/portfolios': typeof DashboardPortfoliosIndexRoute
  '/dashboard/products': typeof DashboardProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/analytics': typeof DashboardAnalyticsRoute
  '/dashboard/api-testing': typeof DashboardApiTestingRoute
  '/dashboard/docs': typeof DashboardDocsRoute
  '/dashboard/explore': typeof DashboardExploreRoute
  '/dashboard/integration': typeof DashboardIntegrationRoute
  '/dashboard/market': typeof DashboardMarketRoute
  '/dashboard/operations': typeof DashboardOperationsRoute
  '/dashboard/product-config': typeof DashboardProductConfigRoute
  '/payment-session/$orderId': typeof PaymentSessionOrderIdRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_authenticated/onboarding/create-product': typeof AuthenticatedOnboardingCreateProductRoute
  '/dashboard/portfolios/$id': typeof DashboardPortfoliosIdRoute
  '/dashboard/products/$productId': typeof DashboardProductsProductIdRoute
  '/dashboard/portfolios/': typeof DashboardPortfoliosIndexRoute
  '/dashboard/products/': typeof DashboardProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/api-testing'
    | '/dashboard/docs'
    | '/dashboard/explore'
    | '/dashboard/integration'
    | '/dashboard/market'
    | '/dashboard/operations'
    | '/dashboard/product-config'
    | '/payment-session/$orderId'
    | '/dashboard/'
    | '/onboarding/create-product'
    | '/dashboard/portfolios/$id'
    | '/dashboard/products/$productId'
    | '/dashboard/portfolios'
    | '/dashboard/products'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo'
    | '/login'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/api-testing'
    | '/dashboard/docs'
    | '/dashboard/explore'
    | '/dashboard/integration'
    | '/dashboard/market'
    | '/dashboard/operations'
    | '/dashboard/product-config'
    | '/payment-session/$orderId'
    | '/dashboard'
    | '/onboarding/create-product'
    | '/dashboard/portfolios/$id'
    | '/dashboard/products/$productId'
    | '/dashboard/portfolios'
    | '/dashboard/products'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/dashboard'
    | '/demo'
    | '/login'
    | '/register'
    | '/dashboard/analytics'
    | '/dashboard/api-testing'
    | '/dashboard/docs'
    | '/dashboard/explore'
    | '/dashboard/integration'
    | '/dashboard/market'
    | '/dashboard/operations'
    | '/dashboard/product-config'
    | '/payment-session/$orderId'
    | '/dashboard/'
    | '/_authenticated/onboarding/create-product'
    | '/dashboard/portfolios/$id'
    | '/dashboard/products/$productId'
    | '/dashboard/portfolios/'
    | '/dashboard/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  PaymentSessionOrderIdRoute: typeof PaymentSessionOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/payment-session/$orderId': {
      id: '/payment-session/$orderId'
      path: '/payment-session/$orderId'
      fullPath: '/payment-session/$orderId'
      preLoaderRoute: typeof PaymentSessionOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/product-config': {
      id: '/dashboard/product-config'
      path: '/product-config'
      fullPath: '/dashboard/product-config'
      preLoaderRoute: typeof DashboardProductConfigRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/operations': {
      id: '/dashboard/operations'
      path: '/operations'
      fullPath: '/dashboard/operations'
      preLoaderRoute: typeof DashboardOperationsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/market': {
      id: '/dashboard/market'
      path: '/market'
      fullPath: '/dashboard/market'
      preLoaderRoute: typeof DashboardMarketRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/integration': {
      id: '/dashboard/integration'
      path: '/integration'
      fullPath: '/dashboard/integration'
      preLoaderRoute: typeof DashboardIntegrationRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/explore': {
      id: '/dashboard/explore'
      path: '/explore'
      fullPath: '/dashboard/explore'
      preLoaderRoute: typeof DashboardExploreRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/docs': {
      id: '/dashboard/docs'
      path: '/docs'
      fullPath: '/dashboard/docs'
      preLoaderRoute: typeof DashboardDocsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/api-testing': {
      id: '/dashboard/api-testing'
      path: '/api-testing'
      fullPath: '/dashboard/api-testing'
      preLoaderRoute: typeof DashboardApiTestingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/analytics': {
      id: '/dashboard/analytics'
      path: '/analytics'
      fullPath: '/dashboard/analytics'
      preLoaderRoute: typeof DashboardAnalyticsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/': {
      id: '/dashboard/products/'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolios/': {
      id: '/dashboard/portfolios/'
      path: '/portfolios'
      fullPath: '/dashboard/portfolios'
      preLoaderRoute: typeof DashboardPortfoliosIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products/$productId': {
      id: '/dashboard/products/$productId'
      path: '/products/$productId'
      fullPath: '/dashboard/products/$productId'
      preLoaderRoute: typeof DashboardProductsProductIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/portfolios/$id': {
      id: '/dashboard/portfolios/$id'
      path: '/portfolios/$id'
      fullPath: '/dashboard/portfolios/$id'
      preLoaderRoute: typeof DashboardPortfoliosIdRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_authenticated/onboarding/create-product': {
      id: '/_authenticated/onboarding/create-product'
      path: '/onboarding/create-product'
      fullPath: '/onboarding/create-product'
      preLoaderRoute: typeof AuthenticatedOnboardingCreateProductRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedOnboardingCreateProductRoute: typeof AuthenticatedOnboardingCreateProductRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOnboardingCreateProductRoute:
    AuthenticatedOnboardingCreateProductRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface DashboardRouteChildren {
  DashboardAnalyticsRoute: typeof DashboardAnalyticsRoute
  DashboardApiTestingRoute: typeof DashboardApiTestingRoute
  DashboardDocsRoute: typeof DashboardDocsRoute
  DashboardExploreRoute: typeof DashboardExploreRoute
  DashboardIntegrationRoute: typeof DashboardIntegrationRoute
  DashboardMarketRoute: typeof DashboardMarketRoute
  DashboardOperationsRoute: typeof DashboardOperationsRoute
  DashboardProductConfigRoute: typeof DashboardProductConfigRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardPortfoliosIdRoute: typeof DashboardPortfoliosIdRoute
  DashboardProductsProductIdRoute: typeof DashboardProductsProductIdRoute
  DashboardPortfoliosIndexRoute: typeof DashboardPortfoliosIndexRoute
  DashboardProductsIndexRoute: typeof DashboardProductsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAnalyticsRoute: DashboardAnalyticsRoute,
  DashboardApiTestingRoute: DashboardApiTestingRoute,
  DashboardDocsRoute: DashboardDocsRoute,
  DashboardExploreRoute: DashboardExploreRoute,
  DashboardIntegrationRoute: DashboardIntegrationRoute,
  DashboardMarketRoute: DashboardMarketRoute,
  DashboardOperationsRoute: DashboardOperationsRoute,
  DashboardProductConfigRoute: DashboardProductConfigRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardPortfoliosIdRoute: DashboardPortfoliosIdRoute,
  DashboardProductsProductIdRoute: DashboardProductsProductIdRoute,
  DashboardPortfoliosIndexRoute: DashboardPortfoliosIndexRoute,
  DashboardProductsIndexRoute: DashboardProductsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  PaymentSessionOrderIdRoute: PaymentSessionOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
